"""Add workflow executions

Revision ID: 31fd435cc36a
Revises: 056676c8604e
Create Date: 2026-07-04 22:30:32.933829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31fd435cc36a'
down_revision: Union[str, Sequence[str], None] = '056676c8604e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflowexecutionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('workflow_execution_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('workflow_node_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'jobs', 'workflow_executions', ['workflow_execution_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'workflow_node_id')
    op.drop_column('jobs', 'workflow_execution_id')
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
