"""Add run_after, retry_policy, last_heartbeat, current_job_id

Revision ID: 3539d364a3fe
Revises: f908861506b3
Create Date: 2026-07-04 11:43:38.024543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3539d364a3fe'
down_revision: Union[str, Sequence[str], None] = 'f908861506b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('run_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('queues', sa.Column('retry_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workers', sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workers', sa.Column('current_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'workers', 'jobs', ['current_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'current_job_id')
    op.drop_column('workers', 'last_heartbeat')
    op.drop_column('queues', 'retry_policy')
    op.drop_column('jobs', 'run_after')
    # ### end Alembic commands ###
