"""Add JobEvent and update Job and Queue

Revision ID: 40232732d02c
Revises: f9671806f7cd
Create Date: 2026-07-04 11:19:30.418468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40232732d02c'
down_revision: Union[str, Sequence[str], None] = 'f9671806f7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_executions', sa.Column('attempt', sa.Integer(), nullable=False))
    op.add_column('job_executions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_executions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_executions', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('job_executions', sa.Column('logs', sa.Text(), nullable=True))
    op.alter_column('job_executions', 'error',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('jobs', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('retries', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.add_column('queues', sa.Column('concurrency_limit', sa.Integer(), nullable=False))
    op.add_column('queues', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('queues', sa.Column('is_paused', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queues', 'is_paused')
    op.drop_column('queues', 'priority')
    op.drop_column('queues', 'concurrency_limit')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_column('jobs', 'idempotency_key')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retries')
    op.drop_column('jobs', 'priority')
    op.alter_column('job_executions', 'error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('job_executions', 'logs')
    op.drop_column('job_executions', 'duration_ms')
    op.drop_column('job_executions', 'completed_at')
    op.drop_column('job_executions', 'started_at')
    op.drop_column('job_executions', 'attempt')
    op.drop_table('job_events')
    # ### end Alembic commands ###
