"""Add slug and org_id

Revision ID: 4f6c852d5617
Revises: 40232732d02c
Create Date: 2026-07-04 11:25:51.555356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6c852d5617'
down_revision: Union[str, Sequence[str], None] = '40232732d02c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('org_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('organization_members_organization_id_fkey'), 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['org_id'], ['id'])
    op.drop_column('organization_members', 'organization_id')
    op.add_column('organizations', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'organizations', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_column('organizations', 'slug')
    op.add_column('organization_members', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_organization_id_fkey'), 'organization_members', 'organizations', ['organization_id'], ['id'])
    op.drop_column('organization_members', 'org_id')
    # ### end Alembic commands ###
