"""Add schedules table

Revision ID: 940aaf164d29
Revises: 81dd29fc75ce
Create Date: 2026-07-04 18:27:45.204459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '940aaf164d29'
down_revision: Union[str, Sequence[str], None] = '81dd29fc75ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('payload_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('schedules', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('schedules', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedules', sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_column('schedules', 'last_run_at')
    op.drop_column('schedules', 'next_run_at')
    op.drop_column('schedules', 'is_active')
    op.drop_column('schedules', 'payload_template')
    # ### end Alembic commands ###
