"""Rename organization_id to org_id in projects

Revision ID: f908861506b3
Revises: 4f6c852d5617
Create Date: 2026-07-04 11:28:48.694180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f908861506b3'
down_revision: Union[str, Sequence[str], None] = '4f6c852d5617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('org_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('projects_organization_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['org_id'], ['id'])
    op.drop_column('projects', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_organization_id_fkey'), 'projects', 'organizations', ['organization_id'], ['id'])
    op.drop_column('projects', 'org_id')
    # ### end Alembic commands ###
